/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[name]` 
  * @property `[age]` 
  * @property `[id]` 
  */
export interface ApiUserListData {
  "name"?: string;
  "age"?: number;
  "id"?: number;
}

