/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `mention` 
  * @property `[lemmaDesc]` 
  * @property `[lemmaId]` 
  * @property `[lemmaTitle]` 
  * @property `[rank]` 
  */
export interface HotspotBrowseShowauditingnewsExtDataRecommends {
  "mention": string;
  "lemmaDesc"?: string;
  "lemmaId"?: number;
  "lemmaTitle"?: string;
  "rank"?: number;
}

