/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[errno]` 
  * @property `[errmsg]` 
  * @property `[data]` 
  */
export interface HotspotApiGetlemmatask {
  "errno"?: number;
  "errmsg"?: string;
  "data"?: models.HotspotApiGetlemmataskData;
}

