/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ajax, { AjaxPromise, ExtraFetchParams } from '@ekit/ajax';
import * as models from '../model/models';

/* tslint:disable:no-unused-variable member-ordering object-literal-shorthand */

/**
  * @description apiUserListGet参数
  * @property `[name]` 用户名称
  * @property `[age]` 用户年龄
  * @property `[id]` 用户ID
  */
export interface ParamsapiUserListGet {
  // queryParams
  /**
   * 用户名称
   */
  name?: string;
  /**
   * 用户年龄
   */
  age?: string;
  /**
   * 用户ID
   */
  id?: string;
}

export class UserApi {
  protected $basePath = ''.replace(/\/$/, '');

  public constructor(basePath?: string) {
    if (basePath !== undefined) {
      this.$basePath = basePath.replace(/\/$/, '');
    }
  }

  /**
   * 
   * @summary 获取用户列表
   * @param params ParamsapiUserListGet
   
   * @param opt ajax config
   * @returns models.ApiUserList
   */
  public apiUserListGet = (
    params: ParamsapiUserListGet,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.ApiUserList>  => {
    const path = '/api/userList';
    const url = this.$basePath + path;
    const p: any = {};
    p.query = {};
    if ('name' in params) p.query.name = params.name;
    if ('age' in params) p.query.age = params.age;
    if ('id' in params) p.query.id = params.id;
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    });
  }
}

export default new UserApi();