/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ajax, { AjaxPromise, ExtraFetchParams } from '@ekit/ajax';
import * as models from '../model/models';

/* tslint:disable:no-unused-variable member-ordering object-literal-shorthand */

/**
  * @description hotspotApiGetlemmataskGet参数
  * @property `Referer` Referer (Only:http://lqxoff.baike.otp.baidu.com/hotspot/home)
  */
export interface ParamshotspotApiGetlemmataskGet {
  // headerParams
  /**
   * Referer (Only:http://lqxoff.baike.otp.baidu.com/hotspot/home)
   */
  Referer: string;
}
/**
  * @description hotspotBrowseShowauditingnewsGet参数
  * @property `limit` 当前展示多少数据
  * @property `offset` 第几页
  * @property `[startTime]` 抓取时间的开始时间
  * @property `[endTime]` 抓取时间的结束时间
  * @property `[startDugTime]` 挖掘时间的开始时间
  * @property `[endDugTime]` 挖掘时间的结束时间
  * @property `[status]` 任务状态
  */
export interface ParamshotspotBrowseShowauditingnewsGet {
  // queryParams
  /**
   * 当前展示多少数据
   */
  limit: string;
  /**
   * 第几页
   */
  offset: string;
  /**
   * 抓取时间的开始时间
   */
  startTime?: string;
  /**
   * 抓取时间的结束时间
   */
  endTime?: string;
  /**
   * 挖掘时间的开始时间
   */
  startDugTime?: string;
  /**
   * 挖掘时间的结束时间
   */
  endDugTime?: string;
  /**
   * 任务状态
   */
  status?: string;
}

export class DefaultApi {
  protected $basePath = ''.replace(/\/$/, '');

  public constructor(basePath?: string) {
    if (basePath !== undefined) {
      this.$basePath = basePath.replace(/\/$/, '');
    }
  }

  /**
   *
   * @summary /hotspot/api/getlemmatask
   * @param params ParamshotspotApiGetlemmataskGet
   * @param opt ajax config
   * @returns models.HotspotApiGetlemmatask
   */
  public hotspotApiGetlemmataskGet = (
    params: ParamshotspotApiGetlemmataskGet,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.HotspotApiGetlemmatask>  => {
    const path = '/hotspot/api/getlemmatask';
    const url = this.$basePath + path;
    const p: any = {};
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    });
  }
  /**
   *
   * @summary 获取所有新闻
   * @param params ParamshotspotBrowseShowauditingnewsGet
   * @param opt ajax config
   * @returns models.HotspotBrowseShowauditingnews
   */
  public hotspotBrowseShowauditingnewsGet = (
    params: ParamshotspotBrowseShowauditingnewsGet,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.HotspotBrowseShowauditingnews>  => {
    const path = '/hotspot/browse/showauditingnews';
    const url = this.$basePath + path;
    const p: any = {};
    p.query = {};
    if ('limit' in params) p.query.limit = params.limit;
    ajax.check(params.limit, 'limit');
    if ('offset' in params) p.query.offset = params.offset;
    ajax.check(params.offset, 'offset');
    if ('startTime' in params) p.query.startTime = params.startTime;
    if ('endTime' in params) p.query.endTime = params.endTime;
    if ('startDugTime' in params) p.query.startDugTime = params.startDugTime;
    if ('endDugTime' in params) p.query.endDugTime = params.endDugTime;
    if ('status' in params) p.query.status = params.status;
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    });
  }
}

export default new DefaultApi();