/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[lid]` 
  * @property `[id]` 
  * @property `[lemmaTitle]` 
  * @property `[level]` 
  * @property `[newLemmaId]` 
  * @property `[adminId]` 
  * @property `[wapId]` 
  * @property `[createTime]` 
  * @property `[receiveTime]` 
  * @property `[updateTime]` 
  * @property `[status]` 
  * @property `[newLemmaStatus]` 
  * @property `[extData]` 
  * @property `[url]` 
  * @property `[website]` 
  * @property `[newsTitle]` 
  * @property `[editorId]` 
  * @property `[category]` 
  * @property `[tag]` 
  * @property `[editTime]` 
  * @property `[tab]` 
  * @property `[taskId]` 
  * @property `[allocateTime]` 
  * @property `[taskStatus]` 
  * @property `[kind]` 
  */
export interface HotspotApiGetlemmataskData {
  "lid"?: number;
  "id"?: number;
  "lemmaTitle"?: string;
  "level"?: number;
  "newLemmaId"?: number;
  "adminId"?: number;
  "wapId"?: number;
  "createTime"?: number;
  "receiveTime"?: number;
  "updateTime"?: number;
  "status"?: number;
  "newLemmaStatus"?: number;
  "extData"?: Array<models.ERRORUNKNOWN>;
  "url"?: string;
  "website"?: string;
  "newsTitle"?: string;
  "editorId"?: number;
  "category"?: string;
  "tag"?: number;
  "editTime"?: number;
  "tab"?: string;
  "taskId"?: number;
  "allocateTime"?: number;
  "taskStatus"?: number;
  "kind"?: string;
}

