/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[id]` 
  * @property `[newsTitle]` 
  * @property `[url]` 
  * @property `[website]` 
  * @property `[category]` 
  * @property `[createTime]` 
  * @property `[updateTime]` 
  * @property `[editorId]` 
  * @property `[status]` 
  * @property `[brief]` 
  * @property `[extData]` 
  * @property `[simCode]` 
  * @property `[tag]` 
  * @property `[valueTag]` 
  * @property `[invalidReason]` 
  * @property `[clusterId]` 
  * @property `[isPrim]` 
  * @property `[dugTime]` 
  * @property `[kind]` 
  * @property `[clusterCnt]` 
  */
export interface HotspotBrowseShowauditingnewsData {
  "id"?: number;
  "newsTitle"?: string;
  "url"?: string;
  "website"?: string;
  "category"?: string;
  "createTime"?: number;
  "updateTime"?: number;
  "editorId"?: number;
  "status"?: number;
  "brief"?: string;
  "extData"?: models.HotspotBrowseShowauditingnewsExtData;
  "simCode"?: string;
  "tag"?: number;
  "valueTag"?: string;
  "invalidReason"?: number;
  "clusterId"?: number;
  "isPrim"?: number;
  "dugTime"?: number;
  "kind"?: string;
  "clusterCnt"?: number;
}

